"$schema" = 'https://starship.rs/config-schema.json'

[character]
error_symbol   = "[✘](bold red)"
success_symbol = '[➜](bold green)' # The 'success_symbol' segment is being set to '➜' with the color 'bold green'
